# kubeProxyReplacement: "false"  # if true, then don't install kube-proxy', and change to --k3s-arg "--disable=kube-proxy@server:*" in k3d
kubeProxyReplacement: "true"  # if true, then don't install kube-proxy', and change to kubeProxyMode to none in kind

k8sServiceHost: k3d-k3s-default-server-0 # use master node in kind network
k8sServicePort: 6443  # use api server port

externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true

# policyEnforcementMode: always

# ingressController:
#   enabled: true
#   default: true
#   enforceHttps: false
#   loadbalancerMode: shared

# nodeinit:
#   enabled: true

l2announcements:
  enabled: true

# l2podAnnouncements:
#   enabled: true

ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"

operator:
  replicas: 1

# bpf:
#   monitorAggregation: none

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      hosts:
        - hubble-192.168.0.100.nip.io

encryption:
  enabled: false
