apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool"
spec:
  blocks:
  - cidr: "172.18.255.200/29"
---
# make this IP address accessible locally by using CiliumL2AnnouncementPolicy
# Layer 2 announcement lets nodes advertise service IPs on the local network using the
# Address Resolution Protocol (ARP) for IPv4 or Neighbor Discovery (ND) for IPv6,1
# so external hosts can reach those IPs without a separate load balancer if they share
# a layer 2 domain
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  loadBalancerIPs: true
  interfaces:
  - eth0
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
